### PR TITLE
RTL, clear screen (with no icon) support 

### PR DESCRIPTION
**Pull request by idodov**
It will be helpful to have those option also:
1. Adding a screen without presence of an icon - just to show the text messenge scrolling.
2.  icon will scroll also as an option how to present a messenge
3. Support for Right to Left scroll (not just left to right direction)
4. Ability to import icons with bitmap code
5. Ability to rainbow the color text (per word or character)

And one last thing if you can add on the readme example how to use the draw_clock service.

### CODE REVIEW

**Comment by lubeda** [comment]
Hi,

*Adding a screen without presence of an icon - just to show the text messenge scrolling*
this will come in 20234.4.0

*icon will scroll also as an option how to present a messenge*
not yet planned

*Support for Right to Left scroll (not just left to right direction)*
good idea i will consider this


*Ability to import icons with bitmap code*
good idea but hard to implement in esphome, since you can access the displaybuffer directly

*Ability to rainbow the color text (per word or character)*
this is not planned

*And one last thing if you can add on the readme example how to use the draw_clock service.*
in 2023.5.0 this will change and will be much clearer, now you should not use draw_clock directly

**Comment by lubeda** [comment]
Hi, 
"Support for Right to Left scroll (not just left to right direction)"  
When i change the scroll direction should the icon also be on the other side? I think this is a request for arab language?

**Comment by idodov** [comment]
For my use case I prefer the icon as it is on the left.  But, it's  a nice feature to have the ability to choose for each screen where to place the icon.

BTW,  will the new version plan to have the ability to create a full screen with text only (no icon)?

**Comment by lubeda** [comment]
"BTW, will the new version plan to have the ability to create a full screen with text only (no icon)?"

Yes, of course

**Pull request closed without merging**
